#!/usr/bin/env python
import sys
import xmlrpclib
import os
if len(sys.argv)>1:
	
	try:
		
		os.mkdir(sys.argv[1]+"n4d-vars")
		f=open(sys.argv[1]+"n4d-vars/vars","w")

		try:
			c=xmlrpclib.ServerProxy("https://localhost:9779")
			vars=c.get_variables("","VariablesManager")
			
			for var in vars:
				f.write(str(var)+"\n")
				for key in vars[var]:
					f.write("\t"+str(key)+"="+str(vars[var][key])+"\n")
			
			
		except Exception as e:
			f.write(str(e)+"\n")
			
		f.close()
		os.mkdir(sys.argv[1]+ "n4d-vars/varsfiles")
		os.system("cp -r /var/lib/n4d/ " + sys.argv[1]+ "n4d-vars/varsfiles/")
	except:
		pass


